#!/usr/bin/env just --justfile
# Documentation: https://just.systems/man/en/

set shell := ['nu', '-c']

# Integration with nodejs package.json scripts, see https://just.systems/man/en/chapter_65.html

export PATH := env('PWD') / 'node_modules/.bin:' + env('PATH')

# Print this help
default:
    @just -l

# Format Justfile
format:
    @just --fmt --unstable

# Install application dependencies
install:
    yarn install

# Run and watch application for development purposes
dev:
    yarn run start

# Update figures
update-figures:
    docker run -u $"(id -u):(id -g)" -v $"($env.PWD):/app" -w /app plantuml/plantuml:1.2024.4 -charset UTF-8 -nbthread auto -failfast2 -tsvg $"-DDATE=(date now | format date "%Y-%m-%d")" figures/*.puml
    rm -rpf ?

# Watch for changes and regenerate figures
watch-figures: update-figures
    watch figures --glob=**/*.puml {|| just update-figures }

# Build production application
build: update-figures
    # #!/usr/share/just-docker/env --image=node:20 bash
    yarn run build

# Serve production application
serve:
    yarn run serve

# Clean files
clean:
    yarn run clear
